{{- if and .Values.app.enabled .Values.serviceAccounts.app.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "commonApp.app.labels" . | nindent 4 }}
  name: {{ template "commonApp.serviceAccountName.app" . }}
  annotations:
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end -}}
